#!/usr/bin/env sh

spacebar -m config position                     bottom
spacebar -m config display                      all
spacebar -m config height                       26
spacebar -m config title                        on
spacebar -m config clock                        on
spacebar -m config power                        on
spacebar -m config dnd                          on
spacebar -m config text_font                    "Hack Nerd Font:Regular:12.0"
spacebar -m config icon_font                    "Hack Nerd Font:Regular:12.0"

# space indicators setting
spacebar -m config spaces                       on
spacebar -m config space_icon_strip             "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  "
spacebar -m config spaces_for_all_displays      on
spacebar -m config space_icon                   
spacebar -m config space_icon_color             0xffd2042d
spacebar -m config space_icon_color_secondary   0xff0437f2
spacebar -m config space_icon_color_tertiary    0xff00a36c

# temporarily we don't need the following
#spacebar -m config display_separator            off
#spacebar -m config display_separator_icon       
#spacebar -m config display_separator_icon_color 0xffffffff

# padding
spacebar -m config padding_left                 20
spacebar -m config padding_right                20
spacebar -m config spacing_left                 20
spacebar -m config spacing_right                20

# colors
spacebar -m config background_color             0xff202020
spacebar -m config foreground_color             0xfffcf5e5
spacebar -m config power_icon_color             0xffcd950c
spacebar -m config battery_icon_color           0xffd75f5f
spacebar -m config dnd_icon_color               0xffa8a8a8
spacebar -m config clock_icon_color             0xff00a36c
spacebar -m config right_shell_icon_color       0xff228b22

# right status segments
spacebar -m config power_icon_strip              
spacebar -m config clock_icon                   
spacebar -m config dnd_icon                     
spacebar -m config clock_format                 "%b %d, %Y | %R"

# we only need right shell to output whoami
spacebar -m config right_shell                  on
spacebar -m config right_shell_icon             
spacebar -m config right_shell_command          "whoami"

echo "spacebar configuration loaded.."
